### ISSUE TITLE
[Doc] How can we use the payload processor to get high throughput for consuming Kafka format data

### ISSUE THREAD

**Issue by codelipenghui** [streamnative/kop#1012]
**Is your feature request related to a problem? Please describe.**
We have added the new feature of the payload processor in Pulsar 2.8.0, and we have implemented a KafkaFormatProcessor in KoP that can be used by users directly to get high throughput for consuming Kafka format data. But I can't find any document related to this part.

**Describe the solution you'd like**
Provide a guide for this part
And it's better to have a tech blog to make a clear picture of the great feature, how to use it and how does it work.

**Comment by BewareMyPower** [comment]
> We have added the new feature of the payload processor in Pulsar 2.8.0

The payload processor was introduced in Pulsar 2.9.0. The docs about how to use it is [here](https://github.com/streamnative/kop/blob/master/docs/configuration.md#performance) because it's only useful when `entryFormat=kafka`.

>  to get high throughput for consuming Kafka format data

It's not proved yet. We need a performance test to measure the performance impact of the `KafkaPayloadProcessor`.
