### ISSUE TITLE
[FEATURE] Verify OauthLoginCallbackHandler works when token expired

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#1261]
**Is your feature request related to a problem? Please describe.**

#1260 implements `lifetimeMs` and `startTimeMs` methods. They are claimed "correctly" but not verified. We need to set up a test to simulate a quickly expired token and verify Kafka clients with the `oauth-client` plugin can refresh the token. Otherwise, we should think of a way to process the token expiration.

**Describe the solution you'd like**
Configure a shorter timeout like 10s in Hydra, and see what will happen.

**Comment by ZiyaoWei** [comment]
Tested out locally and it seems to be working - I changed the timeout to 3 seconds and let the test slept for 10 seconds before sending requests, and it works with a few extra token requests. I'll put that in an actual test and submit a PR.

(It seems when the timeout it set to really low, e.g., 1 second, so that it expires before initialization finishes, the initialization flow will try to use the expired token and fail. I am not sure whether that's worth fixing though.)

**Comment by ZiyaoWei** [comment]
Tested out locally and it seems to be working - I changed the timeout to 3 seconds and let the test slept for 10 seconds before sending requests, and it works with a few extra token requests. I'll put that in an actual test and submit a PR.

There's a different issue - it seems when the timeout it set to really low, e.g., 1 second, so that it expires before initialization finishes, the initialization flow will try to use the expired token and fail. I am not sure whether that's worth fixing though.

**Comment by BewareMyPower** [comment]
> I am not sure whether that's worth fixing though.

I think it is a rare case in real world production environment. IMO it's not worth fixing. We only need to guarantee in this case a correct exception will be thrown so that it can be handled in applications side (for example, recreate the producer).
