### ISSUE TITLE
[BUG] consumer will be cleaned quickly

### ISSUE THREAD

**Issue by dockerzhang** [streamnative/kop#303]
**Describe the bug**
 consumer group be cleaned quickly

**To Reproduce**
1. produce messages using a new topic.
2. consume this topic using a new group name.
3. stop consumer
4. consumer group will be removed in about 10/15 minutes.

**Expected behavior**
consumer group could retain longer.

**Screenshots**
![image](https://user-images.githubusercontent.com/18047329/103508063-69fcba80-4e9b-11eb-91e8-d998e09efbb9.png)

**Comment by WJL3333** [comment]
i found some infomation about it.
when call GroupMetadataManager.cleanupGroupMetadata
the GroupMetadata.removeExpiredOffsets filter offsets that can expire. but when the OffsetAndMetadata.expireTimestamp = -1. GroupMetadata.removeExpiredOffsets remove all the offset for this group. so the group transition to Dead state and being removed by GroupMetadataManager.cleanupGroupMetadata

**Comment by WJL3333** [comment]
the problem is that when we process OffsetCommitRequest. we just use OffsetCommitRequest.PartitionData.timestamp as OffsetAndMetadata.expireTimestamp which is -1. so the logic of GroupMetadataManager.cleanupGroupMetadata can remove all the offset in the coordinator.https://github.com/apache/kafka/blob/ac7b5d3389fddf46bc53ab656de1fa7e2562efdb/core/src/main/scala/kafka/server/KafkaApis.scala#L550

**Comment by BewareMyPower** [comment]
@WJL3333 LGTM. The KoP's `handleOffsetCommitRequest` doesn't handle well for the preprocess of PartitionData.
