### ISSUE TITLE
[BUG] there are topics that do not belong to the KoP namespace if use kafka-topics.sh to create list-request

### ISSUE THREAD

**Issue by dockerzhang** [streamnative/kop#385]
**Describe the bug**
there are topics that do not belong to the KoP namespace if use kafka-topics.sh to create list request.

**To Reproduce**
1. create topics in other pulsar namespaces.
2. list topic use `kafka-topics.sh`
3. See an error

**Expected behavior**
 `kafka-topics.sh` list-request only contains topics that belong to the KoP namespace.

**Screenshots**
only `10pkafka` and `10pkafka1` are KoP topics.
![image](https://user-images.githubusercontent.com/18047329/109117733-57a54b80-777d-11eb-891e-609b0fa1df41.png)

**Comment by BewareMyPower** [comment]
To support multi-tenancy, it needs to find all topics since Kafka has no way to specify namespace. Currently it only filters the `__consumer_offset` topic. I have two suggestions to solve this problem.

1. Add configurations like `kopAllowedNamespaces` to specify a list of namespaces that topics can be accessed. But it would still list all topics across those namespaces.
2. Change the behavior of `handleTopicMetadataRequest`. If users wanted to list topics under a specific namespace, use wildcards symbol, like `public/default/*`.

**Comment by BewareMyPower** [comment]
I'll fix this issue soon.
