### ISSUE TITLE
[BUG] Sarama SDK does not behave as expected using initialPosition=Oldest

### ISSUE THREAD

**Issue by jpenning-tibco** [streamnative/kop#408]
**Describe the bug**
The `initialPosition=Oldest` option does not work as expected using the Sarama integration test. If you run the Sarama integration test repeatedly, messages are re-delivered each time.

* Other SDKs, e.g. Confluent's Go SDK, and the Apache Java SDK work as expected when using `"auto.offset.reset": "earliest"`.
* I have run the Sarama integration test program against a standalone Kafka server and it behaves as expected.
* I have upgraded the integration test go.mod to Sarama 1.28 to no effect.
* I see the same behavior using other Sarama based programs, so this issue is not specific to the integration test.

**To Reproduce**
1. Configure standalone 2.7.1 Pulsar with 2.7.1 KOP.
2. Run the Sarama integration test producer once, sending 10 messages: `KOP_PRODUCE=1 ./sarama-golang`
3. Repeatedly run the consumer: `KOP_CONSUME=1 ./sarama-golang`
4. Every time you run the consumer it will exit after receiving 10 messages.

**Expected behavior**
* The consumer should only exit once and subsequent runs should not receive any messages. The expectation is that for a given groupId messages will not be redelivered once they are marked as committed (`sess.MarkMessage(msg, "")`).

**Comment by BewareMyPower** [comment]
There may be something wrong with the old design of KoP offset and the process of `LIST_OFFSET` request. Maybe some corner cases are not covered.

Since the offset design was changed from https://github.com/streamnative/kop/pull/296 with the latest feature of Pulsar 2.8.0-SNAPSHOT,  we won't pay much attention to maintain the old branches.

You can try latest KoP master with a snapshot release of pulsar (https://github.com/streamnative/pulsar/releases/tag/v2.8.0-rc-202102252222). It works well with go-sarama client.

**Comment by jpenning-tibco** [comment]
Thanks for the quick response. I'll give your suggestion a try.

**Comment by jpenning-tibco** [comment]
Is there a reason you recommended that tag? It's quite a bit behind master. TIA

**Comment by BewareMyPower** [comment]
The KoP master branch is compatible with the next major release of Pulsar, which is 2.8.0 currently. The v2.8.0-rc-xxx is the daily release Pulsar of StreamNative. We usually upgrade KoP's Pulsar dependency to a newer daily release for the latest feature of Pulsar (like #296) or just Pulsar broker has some significant API changes so that KoP cannot run with Pulsar's latest master (like #337).

I've just tested with latest Pulsar ([4d878d7](https://github.com/apache/pulsar/commit/4d878d7dca71e59627f64f122f4e165243b41bf0)), KoP also works. I recommend that tag just because it's KoP's latest dependency now and I'm not sure if Pulsar broker introduced some new API incompatibilities.

**Comment by jpenning-tibco** [comment]
The Sarama SDK works as expected in 2.8 release candidates.
