### ISSUE TITLE
[QUESTION] A puzzle about code logic

### ISSUE THREAD

**Issue by szknb** [streamnative/kop#552]
各位大佬，我在研究KOP的代码时有一点疑问，KafkaCommandDecoder.writeAndFlushResponseToClient这个方法，在每个请求被处理完成后将被调用，在此之前会先将request放入一个队列中，而这个方法会根据队列中request的入队顺序依次检查是否完成，完成才会返回response，也就是说如果前面的请求处理较慢，则会阻塞后面的请求的返回，即使后面的请求早已完成。

我的问题是，这部分逻辑这么设计的原因是什么？我当时以为是需要保证按照KafkaClient的发送顺序返回response，但实际上KafkaClient通过correlationId就能确保request和response正确映射。

感谢各位解惑:)

**Comment by BewareMyPower** [comment]
It's better to use English for conversation since it's an open community for users from all the world.

For your question, Kafka doesn't use correlation id to **guarantee** the response order. Instead, it uses correlation id to **validate** the response order.

You can take https://github.com/streamnative/kop/pull/200 and its linked issue as example.

Kafka's implementation to guarantee the response order is its special network framework design. For a specific connection (channel), the server side will only handle at most one request.

**Comment by szknb** [comment]
Thank you for your answer. I will pay attention to using English later
