### ISSUE TITLE
[BUG] KoP will cause Kafka Errors.REQUEST_TIMED_OUT when consume multi TopicPartition in one comsume request

### ISSUE THREAD

**Issue by crazyinner** [streamnative/kop#604]
**Describe the bug**
When consume multi TopicPartition in one request, in MessageFetchContext.handleFetch(), tryComplete() may enter race condition

When one topicPartition removed from responseData, maybe removed again, which will cause Errors.REQUEST_TIMED_OUT

**Comment by BewareMyPower** [comment]
Is it a code analysis or could it be reproduced? Would you like to contribute a PR so that I can comprehend the bug more clearly?

> When one topicPartition removed from responseData, maybe removed again

No remove operations could be performed with `responseData` in `MessageFetchContext`.

**Comment by wenbingshen** [comment]
@BewareMyPower @crazyinner It has been more than a month since crazyinner raised this question. I can reproduce this problem stably. I tried to complete more logs. From the logs, we can see that the readEntries and CompletableFuture.complete operations for each partition are all performed by BookKeeperClientWorker- Different threads in the OrderedExecutor thread pool are executed. When the partition can read data, because the read data and decode operations will take uncertain time, the competition in this case is relatively weak; and when the partition has no data to write, and the consumer After all the data has been consumed, I have been making empty fetch requests, which can be reproduced stably at this time.
Stable steps to reproduce:
1. A single broker has two partition leaders for one topic;
2. The topic is not writing data, and consumers have consumed the old data;
3. At this time, the consumer client continues to send Fetch requests to broker;
4. Basically, you will soon see that the server returns error_code=7, and the client will down。

1、One fetch request, two partitions, and two threads. The data obtained is an empty set without any protocol conversion operation. 
2、When the BookKeeperClientWorker-OrderedExecutor-25-0 thread adds test_kop_222-3 to the responseData, BookKeeperClientWorker-OrderedExecutor-23- 0 thread adds test_kop_222-3 to responseData, 
3、at this time `responseData.size() >= fetchRequest.fetchData().size()`, because tryComplete has no synchronization operation, two threads enter at the same time, 
4、`fetchRequest.fetchData().keySet() .forEach` two threads traverse at the same time, resulting in the same partition multiple times `responseData.remove(topicPartition)`, partitionData is null and cause the REQUEST_TIMED_OUT error.
