### ISSUE TITLE
[FEATURE] Support non-partitioned topics.

### ISSUE THREAD

**Issue by ronfarkash** [streamnative/kop#674]
**Is your feature request related to a problem? Please describe.**
I believe KoP should support non-partitioned topics. While I understand why only partitioned topics are supported due to offsets, why not treat non partitioned topics as a single partition topic on KoP side?

**Describe the solution you'd like**
When attempting to produce/consume/administrate non-partitioned topics, treat them as a single partitioned topic using an abstraction layer.

**Describe alternatives you've considered**
I have not considered any alternatives worth mentioning.

**Comment by BewareMyPower** [comment]
> While I understand why only partitioned topics are supported due to offsets

I think it's just because the support for partitioned topics is easier to implement. Because when we produce or consume for a topic with only one partition, we can use `topic + "-partition-" + 0` to compute the topic name, then find its owner broker. However, if we want to support non-partitioned topics, we need to find a way to check if it's partitioned. Maybe we can cache the result when a METADATA request arrived. Otherwise each time before produce or consume, the check for whether the topic is partitioned will be an extra cost.
