### ISSUE TITLE
[BUG] Potential memory leak in 2.8.1.10

### ISSUE THREAD

**Issue by MarvinCai** [streamnative/kop#903]
From an env, we saw increased usage of heap memory after enabling KoP and GC is not able to reclaim much memory:
![image](https://user-images.githubusercontent.com/13480084/141674242-aa2363a7-add8-439d-a891-81ec19ce695e.png)
Heap dump indicating it's likely a leak caused by KoP, that's it keep creating persistent cursors without closing any:
![image](https://user-images.githubusercontent.com/13480084/141674255-4e87c4d9-5042-4813-8911-e582ba655c9e.png)

Full dump: https://drive.google.com/file/d/1LBUWAZlfm84YnPGKQRZLyLZQ_tVmpYNG/view?usp=sharing

**Comment by BewareMyPower** [comment]
Though the cursor's name contains "persistent", the cursor is still non-durable cursor. "persistent" is just a part of the full topic name. So when you restart the broker, these cursors should be removed.

There are some bug fixes for cursor leak:
- https://github.com/streamnative/kop/pull/839 in 2.8.1.14, the cursor leak happens when a consumer is closed.
- https://github.com/streamnative/kop/pull/794 in 2.8.1.11, the cursor leak happens when a topic has multiple consumer groups.

**Comment by codelipenghui** [comment]
@MarvinCai Looks like we need to upgrade the customer environment to the latest 2.8.1.x.
