### ISSUE TITLE
[Authorization]  The client  response is none ,after authorization failed. 

### ISSUE THREAD

**Issue by gaozhangmin** [streamnative/kop#904]
I tested with python kafka client.  encountered a produce authorization failure, the client didn't receive any error, Only from debug log, We could know it was authorization failed.

**Comment by BewareMyPower** [comment]
Updated from the private chat:
1. We can test the Java client to verify if it's an issue of Python client because the behavior of Java client is protected by `SaslPlainTestBase#badCredentialFail`.
2. The authentication plugin is customized, so it might be something wrong with the customized authentication provider.

It's an **authentication** error, not an **authorization** error.
